# Generated by Django 3.2.6 on 2021-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
